const products = [
    { 
        '_id': '1',
        'name': 'Apple iphone 13 blue',
        'image': '/images/phones/iphone13_blue_128.jpg',
        'description': 'Mobile Phone',
        'brand': 'Apple',
        'category': 'Mobile',
        'price': 79999,
        'countInStock': 10,
        'rating': 4.7,
        'numReviews': 80,
    },
    { 
        '_id': '2',
        'name': 'Iqoo Z5 5G',
        'image': '/images/phones/iqoo_z5_5g.jpg',
        'description': 'Mobile Phone',
        'brand': 'Iqoo',
        'category': 'Mobile',
        'price': 25000,
        'countInStock': 40,
        'rating': 3.7,
        'numReviews': 110,
    },
    { 
        '_id': '3',
        'name': 'OnePlus Nord CE 2',
        'image': '/images/phones/oneplus_node_ce.jpg',
        'description': 'Mobile Phone',
        'brand': 'OnePlus',
        'category': 'Mobile',
        'price': 28000,
        'countInStock': 35,
        'rating': 4.4,
        'numReviews': 75,
    },
    { 
        '_id': '4',
        'name': 'Pixel 6 5G',
        'image': '/images/phones/pixel_6_5g.jpg',
        'description': 'Mobile Phone',
        'brand': 'Google',
        'category': 'Mobile',
        'price': 65000,
        'countInStock': 19,
        'rating': 4.6,
        'numReviews': 65,
    },
    { 
        '_id': '5',
        'name': 'Xiaomi 11i Camo Green',
        'image': '/images/phones/xiaomi_11i_camo_green.png',
        'description': 'Mobile Phone',
        'brand': 'Xiaomi',
        'category': 'Mobile',
        'price': 32000,
        'countInStock': 110,
        'rating': 4.2,
        'numReviews': 118,
    }
]
export default products